# Site settings
title: Kechi Zhang
email: zhangkechi@pku.edu.cn
description: > # this means to ignore newlines until "baseurl:"
  I'm a PhD Student in the Peking University.
  I am interested in AI4SE & LLMs for Code & Code Generation and Code Representation Based on Deep Learning. 
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://scholar.google.com/citations?user=6AuwtXwAAAAJ&hl=en" # the base hostname & protocol for your site
github_username:  zkcpku
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
theme: minima
